name: Tag and Release

on:
  push:
    branches:
      - main
      - feat/devops

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython

    - name: Determine version type
      id: get-version-type
      run: |
        if [[ $GITHUB_REF == refs/heads/main ]]; then
          echo "::set-output name=version_type::minor"
        elif [[ $GITHUB_REF == refs/heads/feat/devops ]]; then
          echo "::set-output name=version_type::patch"
        else
          echo "::set-output name=version_type::patch"
        fi

    - name: Tag the repo
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python tag_repo.py ${{ steps.get-version-type.outputs.version_type }}
